### ISSUE TITLE
Issues with running for the first time

### ISSUE THREAD

**Issue by tomikjetu** [yournextstore/yournextstore#24]
Hello. 

I cloned the repository and used `pnpm i` and updated the .env file with my public and private keys. Node v22.4.1, pnpm 9.7.1

After running `pnpm dev` this is the error i get `Error: No database connection string was provided to 'neon()'. Perhaps an environment variable has not been set?`

There is nothing about neon in the documentation and nothing about this environment variable. What should I do? I thought the products are loaded from stripe.

Could you please help me resolve this issue? Thank you!

**Comment by RedstonePfalz** [comment]
Can you post your .env file?

**Comment by tomikjetu** [comment]
@RedstonePfalz 

I used the same .env file from the example i cloned, just added the stripe keys and tried editing the experimental corepack

https://github.com/yournextstore/yournextstore/blob/main/.env.example

```
ENABLE_EXPERIMENTAL_COREPACK=0

NEXT_PUBLIC_URL=http://localhost:3000

NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY=pk_live_....
STRIPE_SECRET_KEY=sk_live....
STRIPE_WEBHOOK_SECRET=
STRIPE_CURRENCY=usd
ENABLE_STRIPE_TAX=

NEXT_PUBLIC_LANGUAGE=en

NEXT_PUBLIC_UMAMI_WEBSITE_ID=
```

**Comment by RedstonePfalz** [comment]
I've reconstructed the error:
![image](https://github.com/user-attachments/assets/d82c4ae2-a342-41cd-814e-676a93154ad7)
It occurs with Node 20 and 22
Here is the full error:
```
✓ Ready in 1743ms
 ○ Compiling / ...
 ✓ Compiled / in 9s (1110 modules)
 ⨯ node_modules/.pnpm/@neondatabase+serverless@0.9.4/node_modules/@neondatabase/serverless/index.mjs (1522:23) @ neon
 ⨯ Error: No database connection string was provided to `neon()`. Perhaps an environment variable has not been set?
    at neon (webpack-internal:///(rsc)/./node_modules/.pnpm/@neondatabase+serverless@0.9.4/node_modules/@neondatabase/serverless/index.mjs:1536:35)
    at eval (webpack-internal:///(rsc)/./node_modules/.pnpm/commerce-kit@0.0.16_@neondatabase+serverless@0.9.4_@types+node@20.16.1_next@15.0.0-canary.121_3edth2vbdaxmlrhm6kds5xi2h4/node_modules/commerce-kit/dist/index.js:433:71)
    at (rsc)/./node_modules/.pnpm/commerce-kit@0.0.16_@neondatabase+serverless@0.9.4_@types+node@20.16.1_next@15.0.0-canary.121_3edth2vbdaxmlrhm6kds5xi2h4/node_modules/commerce-kit/dist/index.js (/app/.next/server/vendor-chunks/commerce-kit@0.0.16_@neondatabase+serverless@0.9.4_@types+node@20.16.1_next@15.0.0-canary.121_3edth2vbdaxmlrhm6kds5xi2h4.js:30:1)
    at __webpack_require__ (/app/.next/server/webpack-runtime.js:33:42)
    at eval (webpack-internal:///(rsc)/./src/ui/footer/Footer.tsx:9:70)
    at __webpack_require__.a (/app/.next/server/webpack-runtime.js:100:13)
    at eval (webpack-internal:///(rsc)/./src/ui/footer/Footer.tsx:1:21)
    at (rsc)/./src/ui/footer/Footer.tsx (/app/.next/server/app/(store)/page.js:699:1)
    at __webpack_require__ (/app/.next/server/webpack-runtime.js:33:42)
    at eval (webpack-internal:///(rsc)/./src/app/layout.tsx:19:75)
    at __webpack_require__.a (/app/.next/server/webpack-runtime.js:100:13)
    at eval (webpack-internal:///(rsc)/./src/app/layout.tsx:1:21)
    at (rsc)/./src/app/layout.tsx (/app/.next/server/app/(store)/page.js:574:1)
    at Function.__webpack_require__ (/app/.next/server/webpack-runtime.js:33:42)
    at async getLayoutOrPageModule (/app/node_modules/.pnpm/next@15.0.0-canary.121_@babel+core@7.24.9_babel-plugin-react-compiler@0.0.0-experimental-1f3d_7k2w45fpcym5panvyqrmcq3qly/node_modules/next/dist/compiled/next-server/app-page-experimental.runtime.dev.js:153:154973)
    at async createComponentTreeInternal (/app/node_modules/.pnpm/next@15.0.0-canary.121_@babel+core@7.24.9_babel-plugin-react-compiler@0.0.0-experimental-1f3d_7k2w45fpcym5panvyqrmcq3qly/node_modules/next/dist/compiled/next-server/app-page-experimental.runtime.dev.js:157:16142)
    at async getRSCPayload (/app/node_modules/.pnpm/next@15.0.0-canary.121_@babel+core@7.24.9_babel-plugin-react-compiler@0.0.0-experimental-1f3d_7k2w45fpcym5panvyqrmcq3qly/node_modules/next/dist/compiled/next-server/app-page-experimental.runtime.dev.js:157:66139)
    at async renderToStream (/app/node_modules/.pnpm/next@15.0.0-canary.121_@babel+core@7.24.9_babel-plugin-react-compiler@0.0.0-experimental-1f3d_7k2w45fpcym5panvyqrmcq3qly/node_modules/next/dist/compiled/next-server/app-page-experimental.runtime.dev.js:158:7971)
    at async renderToHTMLOrFlightImpl (/app/node_modules/.pnpm/next@15.0.0-canary.121_@babel+core@7.24.9_babel-plugin-react-compiler@0.0.0-experimental-1f3d_7k2w45fpcym5panvyqrmcq3qly/node_modules/next/dist/compiled/next-server/app-page-experimental.runtime.dev.js:158:2239)
    at async doRender (/app/node_modules/.pnpm/next@15.0.0-canary.121_@babel+core@7.24.9_babel-plugin-react-compiler@0.0.0-experimental-1f3d_7k2w45fpcym5panvyqrmcq3qly/node_modules/next/dist/server/base-server.js:1532:34)
    at async responseGenerator (/app/node_modules/.pnpm/next@15.0.0-canary.121_@babel+core@7.24.9_babel-plugin-react-compiler@0.0.0-experimental-1f3d_7k2w45fpcym5panvyqrmcq3qly/node_modules/next/dist/server/base-server.js:1726:28)
    at async DevServer.renderToResponseWithComponentsImpl (/app/node_modules/.pnpm/next@15.0.0-canary.121_@babel+core@7.24.9_babel-plugin-react-compiler@0.0.0-experimental-1f3d_7k2w45fpcym5panvyqrmcq3qly/node_modules/next/dist/server/base-server.js:1733:28)
    at async DevServer.renderPageComponent (/app/node_modules/.pnpm/next@15.0.0-canary.121_@babel+core@7.24.9_babel-plugin-react-compiler@0.0.0-experimental-1f3d_7k2w45fpcym5panvyqrmcq3qly/node_modules/next/dist/server/base-server.js:2072:24)
    at async DevServer.renderToResponseImpl (/app/node_modules/.pnpm/next@15.0.0-canary.121_@babel+core@7.24.9_babel-plugin-react-compiler@0.0.0-experimental-1f3d_7k2w45fpcym5panvyqrmcq3qly/node_modules/next/dist/server/base-server.js:2110:32)
    at async DevServer.pipeImpl (/app/node_modules/.pnpm/next@15.0.0-canary.121_@babel+core@7.24.9_babel-plugin-react-compiler@0.0.0-experimental-1f3d_7k2w45fpcym5panvyqrmcq3qly/node_modules/next/dist/server/base-server.js:949:25)
    at async NextNodeServer.handleCatchallRenderRequest (/app/node_modules/.pnpm/next@15.0.0-canary.121_@babel+core@7.24.9_babel-plugin-react-compiler@0.0.0-experimental-1f3d_7k2w45fpcym5panvyqrmcq3qly/node_modules/next/dist/server/next-server.js:281:17)
    at async DevServer.handleRequestImpl (/app/node_modules/.pnpm/next@15.0.0-canary.121_@babel+core@7.24.9_babel-plugin-react-compiler@0.0.0-experimental-1f3d_7k2w45fpcym5panvyqrmcq3qly/node_modules/next/dist/server/base-server.js:842:17)
    at async /app/node_modules/.pnpm/next@15.0.0-canary.121_@babel+core@7.24.9_babel-plugin-react-compiler@0.0.0-experimental-1f3d_7k2w45fpcym5panvyqrmcq3qly/node_modules/next/dist/server/dev/next-dev-server.js:378:20
    at async Span.traceAsyncFn (/app/node_modules/.pnpm/next@15.0.0-canary.121_@babel+core@7.24.9_babel-plugin-react-compiler@0.0.0-experimental-1f3d_7k2w45fpcym5panvyqrmcq3qly/node_modules/next/dist/trace/trace.js:157:20)
    at async DevServer.handleRequest (/app/node_modules/.pnpm/next@15.0.0-canary.121_@babel+core@7.24.9_babel-plugin-react-compiler@0.0.0-experimental-1f3d_7k2w45fpcym5panvyqrmcq3qly/node_modules/next/dist/server/dev/next-dev-server.js:375:24)
    at async invokeRender (/app/node_modules/.pnpm/next@15.0.0-canary.121_@babel+core@7.24.9_babel-plugin-react-compiler@0.0.0-experimental-1f3d_7k2w45fpcym5panvyqrmcq3qly/node_modules/next/dist/server/lib/router-server.js:176:21)
    at async handleRequest (/app/node_modules/.pnpm/next@15.0.0-canary.121_@babel+core@7.24.9_babel-plugin-react-compiler@0.0.0-experimental-1f3d_7k2w45fpcym5panvyqrmcq3qly/node_modules/next/dist/server/lib/router-server.js:353:24)
    at async requestHandlerImpl (/app/node_modules/.pnpm/next@15.0.0-canary.121_@babel+core@7.24.9_babel-plugin-react-compiler@0.0.0-experimental-1f3d_7k2w45fpcym5panvyqrmcq3qly/node_modules/next/dist/server/lib/router-server.js:377:13)
    at async Server.requestListener (/app/node_modules/.pnpm/next@15.0.0-canary.121_@babel+core@7.24.9_babel-plugin-react-compiler@0.0.0-experimental-1f3d_7k2w45fpcym5panvyqrmcq3qly/node_modules/next/dist/server/lib/start-server.js:142:13) {
  page: '/',
  digest: '943964342'
}
  1520 | lumn","dataType","constraint","file","line","routine"];function zs(r,{arrayMode:e,
  1521 | fullResults:t,fetchOptions:n,isolationLevel:i,readOnly:s,deferrable:o,queryCallback:u,
> 1522 | resultCallback:c}={}){if(!r)throw new Error("No database connection string was p\
       |                       ^
  1523 | rovided to `neon()`. Perhaps an environment variable has not been set?");let h;try{
  1524 | h=lr(r)}catch{throw new Error("Database connection string provided to `neon()` i\
  1525 | s not a valid URL. Connection string: "+String(r))}let{protocol:l,username:y,password:x,
 ⨯ node_modules/.pnpm/@neondatabase+serverless@0.9.4/node_modules/@neondatabase/serverless/index.mjs (1522:23) @ neon
 ⨯ Error: No database connection string was provided to `neon()`. Perhaps an environment variable has not been set?
    at __webpack_require__ (/app/.next/server/webpack-runtime.js:33:42)
    at eval (./src/ui/footer/Footer.tsx:9:70)
    at __webpack_require__.a (/app/.next/server/webpack-runtime.js:100:13)
    at eval (./src/ui/footer/Footer.tsx:1:21)
    at (rsc)/./src/ui/footer/Footer.tsx (/app/.next/server/app/(store)/page.js:699:1)
    at __webpack_require__ (/app/.next/server/webpack-runtime.js:33:42)
    at eval (./src/app/layout.tsx:19:75)
    at __webpack_require__.a (/app/.next/server/webpack-runtime.js:100:13)
    at eval (./src/app/layout.tsx:1:21)
    at (rsc)/./src/app/layout.tsx (/app/.next/server/app/(store)/page.js:574:1)
    at Function.__webpack_require__ (/app/.next/server/webpack-runtime.js:33:42)
digest: "943964342"
  1520 | lumn","dataType","constraint","file","line","routine"];function zs(r,{arrayMode:e,
  1521 | fullResults:t,fetchOptions:n,isolationLevel:i,readOnly:s,deferrable:o,queryCallback:u,
> 1522 | resultCallback:c}={}){if(!r)throw new Error("No database connection string was p\
       |                       ^
  1523 | rovided to `neon()`. Perhaps an environment variable has not been set?");let h;try{
  1524 | h=lr(r)}catch{throw new Error("Database connection string provided to `neon()` i\
  1525 | s not a valid URL. Connection string: "+String(r))}let{protocol:l,username:y,password:x,
 ○ Compiling /_error ...
 ✓ Compiled /_error in 6.2s (1347 modules)
```

**Comment by tomikjetu** [comment]
@RedstonePfalz Yes, thank you. That's the exact error. What am I missing? Am I supposed to run this kind of database? It wasn't described in the readme file. I don't understand.

**Comment by RedstonePfalz** [comment]
There's no database because Stripe is the backend. This error doesn't occur in a fork of mine, which is 6 commits behind this branch. Try cloning this repository at this point and see if it works: https://github.com/yournextstore/yournextstore/tree/c095c05b6365b0ea58c714e9c905d0cff2aa6c1b
I don't know if Node 22 will work. If an error occurs, try using Node 20.

**Comment by tomikjetu** [comment]
Amazing, Thank you @RedstonePfalz. I managed to get it runnign with the version you've provided. 

But it seems it doesn't work properly for loading the products or filtering categories. Although it connects correctly to the stripe api, asi I can go to /product/[slug]. But /produtcts /category/[slug] or search doesn't output anything. Does this work for you correctly?

**Comment by typeofweb** [comment]
It’s a bug in that we accidentally introduced yesterday an external dependency. Will be fixed today. Sorry for trouble.

**Comment by tomikjetu** [comment]
> It’s a bug in that we accidentally introduced yesterday an external dependency. Will be fixed today. Sorry for trouble.


Thank you, is there any way i can disable caching for commerce-kit?

**Comment by lappemic** [comment]
FYI: Ran also into a similar issue. Working on the commit 2da5372e atm. How can rebase afterwards.

**Comment by zaiste** [comment]
It should be fixed now.
