### ISSUE TITLE
Build Fails Due to Timeout on Certain Pages During Static Generation

### ISSUE THREAD

**Issue by mattyx97** [yournextstore/yournextstore#34]
The build process is failing during the static generation step for certain pages in Next.js application. The issue seems to be related to timeouts, where pages such as /cart, /products, /search, and /cart-overlay are taking longer than 60 seconds to generate, leading to the build process failing after 3 attempts.

Steps to Reproduce:

Run the build command: pnpm run build.
Observe that the build fails during the static generation phase for the aforementioned pages.
Expected Behavior: The build should complete successfully without timing out during the static generation of any pages.

Actual Behavior: The build fails with the following error message after 3 attempts:

pnpm run build

 ```
 ▲ Next.js 15.0.0-canary.138
  - Environments: .env
  - Experiments (use with caution):
    · ppr
    · after
    · turbo
    · reactCompiler
    · scrollRestoration

   Creating an optimized production build ...
 ✓ Compiled successfully

./src/ui/checkout/stripe-elements-container.tsx
31:3  Warning: React Hook useMemo has a missing dependency: 'stripeAccount'. Either include it or remove the dependency array.  react-hooks/exhaustive-deps

info  - Need to disable some ESLint rules? Learn more here: https://nextjs.org/docs/basic-features/eslint#disabling-rules
 ✓ Linting and checking validity of types    
 ⚠ Using edge runtime on a page currently disables static generation for that page
 ✓ Collecting page data    
   Generating static pages (0/17)  [=   ]Using Stripe secret key from env.
   Generating static pages (8/17)  [==  ]Using Stripe secret key from env.
Using Stripe secret key from env.
Using Stripe secret key from env.
Using Stripe secret key from env.
Using Stripe secret key from env.
Using Stripe secret key from env.
Using Stripe secret key from env.
Using Stripe secret key from env.
   Generating static pages (11/17)  [ ===]Failed to build /(store)/page: / (attempt 1 of 3) because it took more than 60 seconds. Retrying again shortly.
   Generating static pages (11/17)  [  ==]Failed to build /(store)/products/page: /products (attempt 1 of 3) because it took more than 60 seconds. Retrying again shortly.
Failed to build /(store)/cart/page: /cart (attempt 1 of 3) because it took more than 60 seconds. Retrying again shortly.
Failed to build /(store)/cart-overlay/page: /cart-overlay (attempt 1 of 3) because it took more than 60 seconds. Retrying again shortly.
Failed to build /(store)/search/page: /search (attempt 1 of 3) because it took more than 60 seconds. Retrying again shortly.
Using Stripe secret key from env.
Using Stripe secret key from env.
Using Stripe secret key from env.
   Generating static pages (11/17)  [   =]Using Stripe secret key from env.
Using Stripe secret key from env.
Using Stripe secret key from env.
Using Stripe secret key from env.
   Generating static pages (11/17)  [=== ]Failed to build /(store)/products/page: /products (attempt 2 of 3) because it took more than 60 seconds. Retrying again shortly.
Using Stripe secret key from env.
Using Stripe secret key from env.
   Generating static pages (11/17)  [ ===]Failed to build /(store)/cart/page: /cart (attempt 2 of 3) because it took more than 60 seconds. Retrying again shortly.
Failed to build /(store)/search/page: /search (attempt 2 of 3) because it took more than 60 seconds. Retrying again shortly.
Failed to build /(store)/page: / (attempt 2 of 3) because it took more than 60 seconds. Retrying again shortly.
Failed to build /(store)/cart-overlay/page: /cart-overlay (attempt 2 of 3) because it took more than 60 seconds. Retrying again shortly.
   Generating static pages (11/17)  [  ==]Using Stripe secret key from env.
Using Stripe secret key from env.
Using Stripe secret key from env.
   Generating static pages (11/17)  [   =]Using Stripe secret key from env.
Using Stripe secret key from env.
   Generating static pages (11/17)  [=   ]Failed to build /(store)/products/page: /products after 3 attempts.

> Build error occurred
Error: Export encountered an error on /(store)/products/page: /products, exiting the build.
    at exportPageWithRetry (/Users/mattiaguariglia/Desktop/yns/yns-store/node_modules/.pnpm/next@15.0.0-canary.138_@babel+core@7.25.2_babel-plugin-react-compiler@0.0.0-experimental-9e96_ppxl42ysmefm6bodpnqinxd6w4/node_modules/next/dist/export/worker.js:291:31)
    at async Promise.all (index 4)
    at async Object.exportPages (/Users/mattiaguariglia/Desktop/yns/yns-store/node_modules/.pnpm/next@15.0.0-canary.138_@babel+core@7.25.2_babel-plugin-react-compiler@0.0.0-experimental-9e96_ppxl42ysmefm6bodpnqinxd6w4/node_modules/next/dist/export/worker.js:315:31) {
  type: 'ExportPageError',
  code: 'NEXT_EXPORT_PAGE_ERROR'
}
```

**Comment by imlizhao** [comment]
![image](https://github.com/user-attachments/assets/21e26fc8-a573-41b7-adf0-f991fc5702fe)
You need to set these in your stripe dashboard

**Comment by zaiste** [comment]
@mattyx97 could you export your products as show below (select **All columns**) and send to us?

![CleanShot 2024-09-16 at 15 24 25@2x](https://github.com/user-attachments/assets/6f30c0fb-05b8-4736-ae3f-ccf560c42428)

**Comment by typeofweb** [comment]
Unfortunately we were not able to reproduce the problem without more information.
