### ISSUE TITLE
TypeError: t.toSorted is not a function in Next.js 15.0.0-canary.196

### ISSUE THREAD

**Issue by mworks-proj** [yournextstore/yournextstore#51]
1. cloned repo
2. ran pnpm install - no errors
3. checked to make sure products in stripe have meta: slug-variable
4. ran pnpm run dev

get the following error

```
yournextstore@1.12.0 dev /path/to/your/project
next dev --turbo

  ▲ Next.js 15.0.0-canary.196 (turbo)
  - Local:        http://localhost:3000
  - Environments: .env
  - Experiments (use with caution):
    · ppr
    · after
    · turbo
    · ...

 ✓ Starting...
Slow filesystem detected. If /path/to/your/project/.next is a network drive, consider moving it to a local folder. If you have an antivirus enabled, consider excluding your project directory.
 ✓ Ready in 1446ms
 ○ Compiling / ...
[BABEL] Note: The code generator has deoptimised the styling of /path/to/your/project/node_modules/.pnpm/next@15.0.0-canary.196_@babel+core@7.25.8_babel-plugin-react-compiler@0.0.0-experimental-fa06_jqkiczct65w45vfnbwmj2bsxba/node_modules/next/dist/compiled/react-dom-experimental/cjs/react-dom-client.development.js as it exceeds the max of 500KB.
 ✓ Compiled / in 12.4s
 ⨯ TypeError: t.toSorted is not a function
    at q (/path/to/your/project/.next/server/chunks/ssr/node_modules__pnpm_14e451._.js:4113:14)
    at Module.Ct (/path/to/your/project/.next/server/chunks/ssr/node_modules__pnpm_14e451._.js:4588:12)
    at async Home (/path/to/your/project/.next/server/chunks/ssr/_b14daa._.js:282:22)
digest: "1963915765"
 GET / 500 in 13589ms
 │ GET https://api.stripe.com/v1/products?limit=100&active=true&expand[0]=data.default_price 200 in 506ms (cache skip)
 │ │ Cache skipped reason: (cache-control: no-cache (hard refresh))
 │ GET https://api.stripe.com/v1/account?expand[0]=settings.branding.logo 200 in 625ms (cache skip)
 │ │ Cache skipped reason: (cache-control: no-cache (hard refresh))
 GET /favicon.ico?favicon.a313b63b.ico 200 in 345ms
 ✓ Compiled /favicon.ico in 425ms
 GET /icon.png?icon.4e1f7e04.png 200 in 303ms
 GET /icon.png?icon.4e1f7e04.png 200 in 89ms
```

**Expected Behavior**

`_The application should compile and run without errors.`

**Actual Behavior_**

```
The server fails to run due to a TypeError: t.toSorted is not a function.
Additional Information
```
**Please provide any additional context or steps that may help in diagnosing the issue.**

**Comment by kai-feinberg** [comment]
I'm getting the same error. How was this solved?

**Comment by typeofweb** [comment]
@kai-feinberg by using Node.js 20 or newer.
