### ISSUE TITLE
t.toSorted is not a function

### ISSUE THREAD

**Issue by kai-feinberg** [yournextstore/yournextstore#53]
Installed dependencies and added products and their slugs to stripe. But after running pnpm install then pnpm dev I'm getting the following error:

 ⨯ TypeError: t.toSorted is not a function
    at q (C:\Users\kaiwf\OneDrive\Desktop\Laude\Laude-store\.next\server\chunks\ssr\node_modules__pnpm_490dbf._.js:4113:14)
    at Module.Ct (C:\Users\kaiwf\OneDrive\Desktop\Laude\Laude-store\.next\server\chunks\ssr\node_modules__pnpm_490dbf._.js:4588:12)
    at async Home (C:\Users\kaiwf\OneDrive\Desktop\Laude\Laude-store\.next\server\chunks\ssr\_7a8144._.js:282:22)
digest: "352614575"
 GET / 500 in 13865ms
 │ GET https://api.stripe.com/v1/account?expand[0]=settings.branding.logo 200 in 199ms (cache hit)
 │ GET https://api.stripe.com/v1/products?limit=100&active=true&expand[0]=data.default_price 200 in 198ms (cache hit)
 ✓ Compiled /favicon.ico in 333ms
 GET /favicon.ico?favicon.a313b63b.ico 200 in 661ms
 GET /favicon.ico?favicon.a313b63b.ico 200 in 324ms
 ○ Compiling /[...segments] ...
 ✓ Compiled /[...segments] in 1652ms

**Comment by zaiste** [comment]
@kai-feinberg try using Node.js 20 or newer.
